name: 'Pull Request CD'

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: |
        # Get GCP credentials
        echo "${KEY}" | base64 -d > ~/key.json
        export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
        cd terraform
        terraform init && terraform validate && terraform apply -auto-approve
      env:
        KEY: ${{secrets.SERVICE_ACCOUNT}}
        GOOGLE_APPLICATION_CREDENTIALS: ~/key.json
